<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zWv6gwa' shared service.

return $this->privates['.service_locator.zWv6gwa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'unavailibilityRepository' => ['privates', 'App\\Repository\\UnavailibilityRepository', 'getUnavailibilityRepositoryService.php', true],
], [
    'unavailibilityRepository' => 'App\\Repository\\UnavailibilityRepository',
]);
