<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.00Wei2p' shared service.

return $this->privates['.service_locator.00Wei2p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'unavailibility' => ['privates', '.errored..service_locator.00Wei2p.App\\Entity\\Unavailibility', NULL, 'Cannot autowire service ".service_locator.00Wei2p": it references class "App\\Entity\\Unavailibility" but no such service exists.'],
], [
    'unavailibility' => 'App\\Entity\\Unavailibility',
]);
