<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKOlSpx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKOlSpx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKOlSpx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKOlSpx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXKOlSpx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XKOlSpx',
    'container.build_id' => '9c11a820',
    'container.build_time' => 1574260743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKOlSpx');
