<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCVZP6wh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCVZP6wh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCVZP6wh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCVZP6wh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCVZP6wh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CVZP6wh',
    'container.build_id' => '55f8169c',
    'container.build_time' => 1574429113,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCVZP6wh');
