<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE8MyGvg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE8MyGvg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE8MyGvg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE8MyGvg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE8MyGvg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E8MyGvg',
    'container.build_id' => '939817e1',
    'container.build_time' => 1573818158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE8MyGvg');
